import Head from 'next/head'
import Image from 'next/image'
import ButtonOutline from '../components/ButtonOutline'
import Button from '../components/Button'
import ladingIllustrastion from '/public/illustrations/landing.svg'
import { FaChevronDown } from 'react-icons/fa'
import signupicon from '/public/icons/things_to_do_signup.svg'
import moneyicon from '/public/icons/things_to_do_money.svg'
import travelicon from '/public/icons/things_to_do_travel.svg'
import { getNames } from 'country-list'
import { useRouter } from 'next/router'
import { getCampgrounds } from '../util/campgrounds'
import CampgroundCard from '../components/CampgroundCard'
import ComboBox from '../components/ComboBox'
import Datepicker from 'react-tailwindcss-datepicker'
import { useState } from 'react'
import Campground from '../models/Campground'
import Link from 'next/link'
import airplanes from '/public/planes.svg'
import trees from '/public/coconut-trees.svg'
import largePlanes from '/public/large_planes.svg'

export default function Home({ camps, discountCamps = [] }) {
  const router = useRouter()

  const countries = getNames().map(country => ({
    text: country,
    disable: false,
  }))

  const [date, setDate] = useState('')
  const [location, setLocation] = useState({ text: 'Location', disable: true })
  const [guests, setGuests] = useState({ text: 'Guests', disable: true })

  const search = e => {
    e.preventDefault()

    router.push(
      `/campgrounds?location=${location.text}&date=${date}&guests=${guests.text}`
    )
  }

  const renderTopCampgrounds = camps.map(camp => (
    <CampgroundCard key={camp._id} campground={camp} />
  ))

  const renderDiscountCampgrounds = discountCamps.map(camp => (
    <CampgroundCard key={camp._id} campground={camp} />
  ))

  return (
    <>
      <Head>
        <title>Tripmates | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='z-10 grid gap-10 py-10 lg:gap-16 lg:py-16'>
        <div className='flex flex-col gap-10 md:flex-row'>
          <div className='flex-1'>
            <h3 className='mb-5 font-volkhov text-4xl font-bold leading-tight lg:text-5xl lg:leading-snug xl:mb-10 xl:text-6xl'>
              Get started your exciting{' '}
              <span className='text-brand '>journey</span> with us.
            </h3>
            <p className='mb-10 text-paragraph lg:text-lg lg:leading-loose xl:mb-16 xl:text-xl xl:leading-loose'>
              A Team of experienced tourism professionals will provide you with
              the best advice and tips for your desire place.
            </p>
            <Link href={'/campgrounds'}>
              <ButtonOutline text='Discover Now' />
            </Link>
          </div>
          <div className='relative flex-1'>
            <Image
              src={largePlanes}
              className='absolute -top-10 z-[-1] lg:scale-125'
            />
            <Image
              className='w-sm md:w-full'
              src={ladingIllustrastion}
              alt='df'
            />
          </div>
        </div>
        <form
          className='mx-auto flex max-w-screen-md flex-wrap items-center gap-8 rounded-lg bg-[#fff] p-6 drop-shadow-xl md:flex-row md:justify-around md:py-8'
          onSubmit={search}
        >
          {/* LOCATION */}
          <div className='flex w-max flex-col items-start gap-1'>
            <div className='flex max-w-[8.75rem] items-center gap-1'>
              <ComboBox
                list={[{ text: 'Location', disable: true }, ...countries]}
                selected={location}
                setSelected={setLocation}
              />
              <label htmlFor='location' className='cursor-pointer'>
                <FaChevronDown className='text-xs text-brand' />
              </label>
            </div>
            <p className='text-sm text-paragraph'>Where are you going</p>
          </div>
          {/* DATE */}
          <div className='flex flex-col items-start gap-1'>
            <div className='flex max-w-[8.75rem] items-center gap-2'>
              <div className='relative'>
                <Datepicker
                  primaryColor='green'
                  onChange={val => setDate(val.startDate)}
                  asSingle={true}
                  useRange={false}
                  inputClassName='opacity-0 !p-0 cursor-pointer h-full'
                  toggleClassName='opacity-0 pointer-events-none'
                  containerClassName='w-full'
                />
              </div>
              <label className='pointer-events-none absolute'>
                {!!date ? date : 'Date'}
              </label>
              <label htmlFor='date' className='cursor-pointer'>
                <FaChevronDown className='text-xs text-brand' />
              </label>
            </div>
            <p className='text-sm text-paragraph'>When will you go</p>
          </div>
          {/* GUESTS */}
          <div className='flex flex-col items-start gap-1'>
            <div className='flex max-w-[8.75rem] items-center gap-2'>
              <ComboBox
                list={[
                  { text: 'Guests', disable: true },
                  { text: '1 Guests', disable: false },
                  { text: '2 Guests', disable: false },
                  { text: '3 Guests', disable: false },
                  { text: '3+ Guests', disable: false },
                ]}
                selected={guests}
                setSelected={setGuests}
              />
              <label htmlFor='guests' className='cursor-pointer'>
                <FaChevronDown className='text-xs text-brand' />
              </label>
            </div>
            <p className='text-sm text-paragraph'>Number of guests</p>
          </div>
          <Button text='Explore Now' />
        </form>
      </section>
      <section className='bg-bleed relative bg-secondaryBg p-7 md:p-12 lg:p-16'>
        <Image
          src={airplanes}
          className='absolute right-0 z-[-1] w-36 lg:right-[10%]'
        />
        <h3 className='mb-2 text-center font-volkhov text-2xl font-extrabold md:mb-4 md:text-3xl lg:mb-6 lg:text-4xl'>
          Things you need <span className='text-brand'>to do</span>
        </h3>
        <p className='mx-auto mb-5 text-center text-base text-paragraph md:mb-10 md:max-w-lg lg:mb-14'>
          We ensure that you&apos;ll embark on a perfectly planned, safe
          vacation at a price you can afford.
        </p>
        <div className='flex flex-wrap justify-center gap-5'>
          <div className='max-w-xs rounded-lg bg-white bg-[url("/illustrations/signup_wave.svg")] bg-cover px-8 py-10 shadow-lg'>
            <Image src={signupicon} alt='sign up icon' className='mb-4' />
            <h5 className='mb-2 text-lg font-bold'>Sign Up</h5>
            <p className='text-sm text-paragraph'>
              Completes all the work associated with planning and processing
            </p>
          </div>
          <div className='max-w-xs rounded-lg bg-white bg-[url("/illustrations/money_wave.svg")] bg-cover px-8 py-10 shadow-lg'>
            <Image src={moneyicon} alt='sign up icon' className='mb-4' />
            <h5 className='mb-2 text-lg font-bold'>Worth of Money</h5>
            <p className='text-sm text-paragraph'>
              After successful access then book from exclusive deals & pricing
            </p>
          </div>
          <div className='max-w-xs rounded-lg bg-white bg-[url("/illustrations/travel_wave.svg")] bg-cover px-8 py-10 shadow-lg'>
            <Image src={travelicon} alt='sign up icon' className='mb-4' />
            <h5 className='mb-2 text-lg font-bold'>Exciting Travel</h5>
            <p className='text-sm text-paragraph'>
              Start and explore a wide range of exciting travel experience.
            </p>
          </div>
        </div>
      </section>
      {/* Top Camps */}
      <section className='p-7 md:p-12 lg:p-16'>
        <h3 className='mb-2 text-center font-volkhov text-2xl font-extrabold md:mb-4 md:text-3xl lg:mb-6 lg:text-4xl'>
          Top rated campgrounds on <span className='text-brand'>Tripmates</span>
        </h3>
        <p className='mx-auto mb-5 text-center text-base text-paragraph md:mb-10 md:max-w-lg lg:mb-14'>
          Discover our fantastic campgrounds & start planning your journey.
        </p>
        <div className='grid w-full gap-6 md:grid-cols-2 lg:grid-cols-3'>
          {renderTopCampgrounds}
        </div>
      </section>
      {/* Discount camps */}
      {!!discountCamps.length && (
        <section className='relative p-7 md:p-12 lg:p-16'>
          <Image src={trees} className='absolute top-20 right-0 lg:right-36' />
          <h3 className='mb-2 text-center font-volkhov text-2xl font-extrabold md:mb-4 md:text-3xl lg:mb-6 lg:text-4xl'>
            Exclusive <span className='text-brand'>deals & discounts</span>
          </h3>
          <p className='mx-auto mb-5 text-center text-base text-paragraph md:mb-10 md:max-w-lg lg:mb-14'>
            Discover our fantastic exclusive booking discounts & start planning
            your journey.
          </p>
          <div className='grid w-full gap-6 md:grid-cols-2 lg:grid-cols-3'>
            {renderDiscountCampgrounds}
          </div>
        </section>
      )}
    </>
  )
}

export async function getServerSideProps(context) {
  const camps = await getCampgrounds({ sort: 'rating', limit: 3 })

  const discountCamps = await Campground.find({})
    .where('price.discount')
    .gt('0')

  return {
    props: { camps, discountCamps: JSON.parse(JSON.stringify(discountCamps)) },
  }
}

// TODO: CRUD

// C -> POST  /campgrounds       ✅
// R -> GET   /campgrounds       ✅
// U -> PATCH /campgrounds/[id]  ✅
// D -> DELETE /campgrounds/[id] ✅
